name: Checks

on:
  pull_request:
    types: [ opened, synchronize ]

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup npm
        run: |
          npm set scripts-prepend-node-path=true

      - name: Install dependencies
        run: |
          npx lerna bootstrap --ci

      - uses: microsoft/playwright-github-action@v1

      - name: Format and test
        run: |
          yarn format
          yarn test:pre-push
