name: Checks

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check for skip lerna in commit message
        id: check_skip
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" == *"[skip lerna]"* ]]; then
            echo "::set-output name=SKIP_LERNA::true"
          else
            echo "::set-output name=SKIP_LERNA::false"
          fi

      - name: Checkout
        if: steps.check_skip.outputs.SKIP_LERNA == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 20
        if: steps.check_skip.outputs.SKIP_LERNA == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        if: steps.check_skip.outputs.SKIP_LERNA == 'false'
        run: |
          npm ci --legacy-peer-deps

      - name: Install playwright
        if: steps.check_skip.outputs.SKIP_LERNA == 'false'
        run: |
          npx playwright install chromium webkit --with-deps

      - name: Format and test
        if: steps.check_skip.outputs.SKIP_LERNA == 'false'
        run: |
          npm run format
          npm run test:pre-push
