name: Checks

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npx lerna@6.6.2 bootstrap --ci

      - name: Install playwright
        run: |
          npx playwright install chromium webkit --with-deps

      - name: Format and test
        run: |
          npm run format
          npm run test:pre-push
