name: Checks

on:
  pull_request:
    types: [ opened, synchronize ]

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Setup npm
        run: |
          npm set scripts-prepend-node-path=true

      - name: Install dependencies
        run: |
          npx lerna bootstrap --ci

      - uses: microsoft/playwright-github-action@v2

      - name: Format and test
        run: |
          npm run format
          npm run test:pre-push
